# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tyqca/OneDrive/School/Labs/1195_Labs/Lab_1_adderSubtractor/Lab_1_adderSubtractor.srcs/sources_1/bd/Lab_1_adderSub/ip/Lab_1_adderSub_rst_ps7_0_100M_1/Lab_1_adderSub_rst_ps7_0_100M_1.xci
# IP: The module: 'Lab_1_adderSub_rst_ps7_0_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tyqca/OneDrive/School/Labs/1195_Labs/Lab_1_adderSubtractor/Lab_1_adderSubtractor.srcs/sources_1/bd/Lab_1_adderSub/ip/Lab_1_adderSub_rst_ps7_0_100M_1/Lab_1_adderSub_rst_ps7_0_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_1_adderSub_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tyqca/OneDrive/School/Labs/1195_Labs/Lab_1_adderSubtractor/Lab_1_adderSubtractor.srcs/sources_1/bd/Lab_1_adderSub/ip/Lab_1_adderSub_rst_ps7_0_100M_1/Lab_1_adderSub_rst_ps7_0_100M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_1_adderSub_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tyqca/OneDrive/School/Labs/1195_Labs/Lab_1_adderSubtractor/Lab_1_adderSubtractor.srcs/sources_1/bd/Lab_1_adderSub/ip/Lab_1_adderSub_rst_ps7_0_100M_1/Lab_1_adderSub_rst_ps7_0_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_1_adderSub_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/tyqca/OneDrive/School/Labs/1195_Labs/Lab_1_adderSubtractor/Lab_1_adderSubtractor.srcs/sources_1/bd/Lab_1_adderSub/ip/Lab_1_adderSub_rst_ps7_0_100M_1/Lab_1_adderSub_rst_ps7_0_100M_1.xci
# IP: The module: 'Lab_1_adderSub_rst_ps7_0_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tyqca/OneDrive/School/Labs/1195_Labs/Lab_1_adderSubtractor/Lab_1_adderSubtractor.srcs/sources_1/bd/Lab_1_adderSub/ip/Lab_1_adderSub_rst_ps7_0_100M_1/Lab_1_adderSub_rst_ps7_0_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_1_adderSub_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tyqca/OneDrive/School/Labs/1195_Labs/Lab_1_adderSubtractor/Lab_1_adderSubtractor.srcs/sources_1/bd/Lab_1_adderSub/ip/Lab_1_adderSub_rst_ps7_0_100M_1/Lab_1_adderSub_rst_ps7_0_100M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_1_adderSub_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tyqca/OneDrive/School/Labs/1195_Labs/Lab_1_adderSubtractor/Lab_1_adderSubtractor.srcs/sources_1/bd/Lab_1_adderSub/ip/Lab_1_adderSub_rst_ps7_0_100M_1/Lab_1_adderSub_rst_ps7_0_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_1_adderSub_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
