# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tyqca/OneDrive/School/Labs/1195_Labs/Lab_3/Lab_3.srcs/sources_1/bd/lab_3/ip/lab_3_rst_ps7_0_50M_0/lab_3_rst_ps7_0_50M_0.xci
# IP: The module: 'lab_3_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tyqca/OneDrive/School/Labs/1195_Labs/Lab_3/Lab_3.srcs/sources_1/bd/lab_3/ip/lab_3_rst_ps7_0_50M_0/lab_3_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_3_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tyqca/OneDrive/School/Labs/1195_Labs/Lab_3/Lab_3.srcs/sources_1/bd/lab_3/ip/lab_3_rst_ps7_0_50M_0/lab_3_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_3_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tyqca/OneDrive/School/Labs/1195_Labs/Lab_3/Lab_3.srcs/sources_1/bd/lab_3/ip/lab_3_rst_ps7_0_50M_0/lab_3_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_3_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/tyqca/OneDrive/School/Labs/1195_Labs/Lab_3/Lab_3.srcs/sources_1/bd/lab_3/ip/lab_3_rst_ps7_0_50M_0/lab_3_rst_ps7_0_50M_0.xci
# IP: The module: 'lab_3_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tyqca/OneDrive/School/Labs/1195_Labs/Lab_3/Lab_3.srcs/sources_1/bd/lab_3/ip/lab_3_rst_ps7_0_50M_0/lab_3_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_3_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tyqca/OneDrive/School/Labs/1195_Labs/Lab_3/Lab_3.srcs/sources_1/bd/lab_3/ip/lab_3_rst_ps7_0_50M_0/lab_3_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_3_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/tyqca/OneDrive/School/Labs/1195_Labs/Lab_3/Lab_3.srcs/sources_1/bd/lab_3/ip/lab_3_rst_ps7_0_50M_0/lab_3_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_3_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
