# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Pre_Lab_1/PYNQ-Z1_C.xdc

# Block Designs: bd/Lab_1_adderSub/Lab_1_adderSub.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_1_adderSub || ORIG_REF_NAME==Lab_1_adderSub} -quiet] -quiet

# IP: bd/Lab_1_adderSub/ip/Lab_1_adderSub_Full_Adder_Subtracto_0_0/Lab_1_adderSub_Full_Adder_Subtracto_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_1_adderSub_Full_Adder_Subtracto_0_0 || ORIG_REF_NAME==Lab_1_adderSub_Full_Adder_Subtracto_0_0} -quiet] -quiet

# IP: bd/Lab_1_adderSub/ip/Lab_1_adderSub_processing_system7_0_1/Lab_1_adderSub_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_1_adderSub_processing_system7_0_1 || ORIG_REF_NAME==Lab_1_adderSub_processing_system7_0_1} -quiet] -quiet

# IP: bd/Lab_1_adderSub/ip/Lab_1_adderSub_axi_regmap_0_1/Lab_1_adderSub_axi_regmap_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_1_adderSub_axi_regmap_0_1 || ORIG_REF_NAME==Lab_1_adderSub_axi_regmap_0_1} -quiet] -quiet

# IP: bd/Lab_1_adderSub/ip/Lab_1_adderSub_ps7_0_axi_periph_1/Lab_1_adderSub_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_1_adderSub_ps7_0_axi_periph_1 || ORIG_REF_NAME==Lab_1_adderSub_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/Lab_1_adderSub/ip/Lab_1_adderSub_rst_ps7_0_100M_1/Lab_1_adderSub_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_1_adderSub_rst_ps7_0_100M_1 || ORIG_REF_NAME==Lab_1_adderSub_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/Lab_1_adderSub/ip/Lab_1_adderSub_auto_pc_0/Lab_1_adderSub_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_1_adderSub_auto_pc_0 || ORIG_REF_NAME==Lab_1_adderSub_auto_pc_0} -quiet] -quiet

# XDC: bd/Lab_1_adderSub/Lab_1_adderSub_ooc.xdc
